### ISSUE TITLE
Idea: detect spam/robot updates

### ISSUE THREAD

**Issue by stact** [Nushio/historian#1]
Hi,

Is it possible to have the user id who updates the record?
It will allow to detect if it's a spam.

Other idea maybe, is to have another extension to do that. What do you think?

* Spam detection on number of records last x minutes
* Business rules to don't allow write (until a configurable delay)

**Comment by Nushio** [comment]
Hi! For some reason, github didn't notify me of this so I hadn't seen it, sorry for the delay!

Firestore's event api does not state who or what triggered the write. What we do alongside this extension is that writes by our app always include an updatedBy field (which could be spoofed, sure), but in 99% of the cases, this is enough for us.

As for Spam Detection, try App Check! The goal of AppCheck is to prohibit writes/reads from unauthorized devices. 
We haven't seen the need for an extension to deal with spam just yet.
